# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-11 15:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_date_and_time', models.DateTimeField(blank=True, null=True, verbose_name='visitation date and time')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(default='', max_length=80, verbose_name='Name of disease')),
                ('description', models.TextField(default='', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('NIS', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80, null=True)),
                ('last_name', models.CharField(max_length=80, null=True)),
                ('contact', models.CharField(max_length=15, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('The patient is', 'The patient is'), ('Male', 'Male'), ('Female', 'Female')], default='The patient is', max_length=2)),
                ('born', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(default='', max_length=80, verbose_name='Name of symptom')),
                ('description', models.TextField(default='', max_length=1000)),
                ('patient', models.ManyToManyField(through='script.Consultation', to='script.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(default='', max_length=80, verbose_name='Name of treatment')),
                ('description', models.TextField(default='', max_length=5000)),
                ('disease', models.ManyToManyField(through='script.Consultation', to='script.Disease')),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='symptom',
            field=models.ManyToManyField(to='script.Symptom'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script.Symptom'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient_disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script.Disease'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient_identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script.Patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient_treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script.Treatment'),
        ),
    ]
