# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-11 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('The patient is', 'The patient is'), ('Male', 'Male'), ('Female', 'Female')], default='The patient is', max_length=100),
        ),
    ]
